/**
 * Friendly, named enums for profile preferences. Each enum **value is the raw
 * Tinder id**, so you can pass either the enum member (e.g. `UserInterest.Yoga`)
 * or the raw string (`'it_42'`) interchangeably.
 *
 * Types here accept both forms (`Enum | RawId`); the adapters forward the value
 * as-is since an enum member already equals its id string at runtime.
 */
import type { ChoiceIdOf, InterestId } from '@/dictionaries.ts';

/** An interest, either as a named member or a raw `it_*` id. */
export type InterestInput = UserInterest | InterestId;

/**
 * ISO 639-1 two-letter language codes used by global mode
 * (`global_mode.language_preferences[].language`), e.g. `'es'`, `'en'`.
 */
export const GLOBAL_MODE_LANGUAGES = [
    'aa', 'ab', 'ae', 'af', 'ak', 'am', 'an', 'ar', 'as', 'av', 'ay', 'az',
    'ba', 'be', 'bg', 'bh', 'bi', 'bm', 'bn', 'bo', 'br', 'bs',
    'ca', 'ce', 'ch', 'co', 'cr', 'cs', 'cu', 'cv', 'cy',
    'da', 'de', 'dv', 'dz',
    'ee', 'el', 'en', 'eo', 'es', 'et', 'eu',
    'fa', 'ff', 'fi', 'fj', 'fo', 'fr', 'fy',
    'ga', 'gd', 'gl', 'gn', 'gu', 'gv',
    'ha', 'he', 'hi', 'ho', 'hr', 'ht', 'hu', 'hy', 'hz',
    'ia', 'id', 'ie', 'ig', 'ii', 'ik', 'io', 'is', 'it', 'iu',
    'ja', 'jv',
    'ka', 'kg', 'ki', 'kj', 'kk', 'kl', 'km', 'kn', 'ko', 'kr', 'ks', 'ku', 'kv', 'kw', 'ky',
    'la', 'lb', 'lg', 'li', 'ln', 'lo', 'lt', 'lu', 'lv',
    'mg', 'mh', 'mi', 'mk', 'ml', 'mn', 'mr', 'ms', 'mt', 'my',
    'na', 'nb', 'nd', 'ne', 'ng', 'nl', 'nn', 'no', 'nr', 'nv', 'ny',
    'oc', 'oj', 'om', 'or', 'os',
    'pa', 'pi', 'pl', 'ps', 'pt',
    'qu',
    'rm', 'rn', 'ro', 'ru', 'rw',
    'sa', 'sc', 'sd', 'se', 'sg', 'si', 'sk', 'sl', 'sm', 'sn', 'so', 'sq', 'sr', 'ss', 'st', 'su', 'sv', 'sw',
    'ta', 'te', 'tg', 'th', 'ti', 'tk', 'tl', 'tn', 'to', 'tr', 'ts', 'tt', 'tw', 'ty',
    'ug', 'uk', 'ur', 'uz',
    've', 'vi', 'vo',
    'wa', 'wo',
    'xh',
    'yi', 'yo',
    'za', 'zh', 'zu',
] as const;

/** An ISO 639-1 two-letter language code accepted by global mode. */
export type GlobalModeLanguage = typeof GLOBAL_MODE_LANGUAGES[number];

/**
 * All selectable interests (`it_*`), keyed by a friendly English name.
 * Value = the Tinder interest id.
 */
export enum UserInterest {
    Coffee = 'it_1',
    Brunch = 'it_10',
    Parties = 'it_1001',
    Sailing = 'it_1005',
    Surfing = 'it_1013',
    Tattoos = 'it_1014',
    Skiing = 'it_1021',
    Snowboarding = 'it_1022',
    Festivals = 'it_1024',
    EscapeRooms = 'it_11',
    Shopping = 'it_14',
    SelfLove = 'it_1430',
    WalkingMyDog = 'it_15',
    Exhibitions = 'it_16',
    FoodTours = 'it_19',
    BoardGames = 'it_2002',
    Trivia = 'it_2003',
    CraftBeer = 'it_2004',
    Tea = 'it_2005',
    Wine = 'it_2006',
    Vlogging = 'it_2007',
    Volunteering = 'it_2008',
    Environmentalism = 'it_2009',
    Cooking = 'it_2010',
    Astrology = 'it_2011',
    Gardening = 'it_2013',
    Art = 'it_2014',
    Football = 'it_2015',
    Dancing = 'it_2016',
    Museums = 'it_2017',
    Activism = 'it_2018',
    Politics = 'it_2019',
    JPop = 'it_2022',
    Cricket = 'it_2023',
    Bollywood = 'it_2024',
    Poetry = 'it_2028',
    StandUpComedy = 'it_2029',
    HipHop = 'it_2030',
    HouseParties = 'it_2031',
    Generation90s = 'it_2033',
    Sushi = 'it_2035',
    Sneakers = 'it_2039',
    CountryMusic = 'it_2048',
    AmericanFootball = 'it_2049',
    RoadTrips = 'it_2050',
    ThriftShopping = 'it_2051',
    BlackLivesMatter = 'it_2052',
    VotingRights = 'it_2053',
    ClimateChange = 'it_2054',
    MentalHealthAwareness = 'it_2055',
    LgbtqiaRights = 'it_2057',
    Feminism = 'it_2058',
    Nba = 'it_2062',
    Mlb = 'it_2063',
    BubbleTea = 'it_2067',
    Badminton = 'it_2069',
    Cars = 'it_2072',
    Clubbing = 'it_2075',
    StreetFood = 'it_2079',
    HorrorMovies = 'it_2080',
    Boxing = 'it_2081',
    Rugby = 'it_2090',
    Tarot = 'it_2094',
    Acai = 'it_2095',
    Bars = 'it_2098',
    FunkMusic = 'it_2099',
    Partygoer = 'it_2105',
    BeachBars = 'it_2106',
    Grime = 'it_2107',
    NinetiesBritpop = 'it_2108',
    Upcycling = 'it_2109',
    PubQuiz = 'it_2113',
    ESports = 'it_2117',
    Motorsports = 'it_2119',
    Podcasts = 'it_2121',
    Pubs = 'it_2123',
    Barbecue = 'it_2125',
    Pho = 'it_2129',
    Motorcycles = 'it_2133',
    SelfCare = 'it_2155',
    Basketball = 'it_2156',
    Theater = 'it_2157',
    Meditation = 'it_2159',
    Tennis = 'it_2161',
    HappyHour = 'it_2163',
    Couchsurfing = 'it_2166',
    VintageFashion = 'it_2171',
    Reggaeton = 'it_2172',
    PlantBased = 'it_2190',
    Acapella = 'it_2201',
    AmongUs = 'it_2202',
    Archery = 'it_2205',
    ArtGalleries = 'it_2206',
    Atari = 'it_2208',
    Backpacking = 'it_2209',
    Bands = 'it_2212',
    GoingForDrinks = 'it_2213',
    Baseball = 'it_2214',
    BingeWatching = 'it_2221',
    Bowling = 'it_2228',
    Canoeing = 'it_2232',
    CarRacing = 'it_2233',
    Cheerleading = 'it_2235',
    Choir = 'it_2236',
    ContentCreation = 'it_2238',
    Cosplay = 'it_2239',
    DisabilityRights = 'it_2243',
    Drawing = 'it_2245',
    OutdoorCinema = 'it_2246',
    DungeonsAndDragons = 'it_2248',
    /** Duplicate label of {@link UserInterest.ElectronicMusic} (`it_6056`). */
    ElectronicMusicAlt = 'it_2249',
    Entrepreneurship = 'it_2251',
    Equality = 'it_2253',
    Equestrian = 'it_2254',
    ExchangePrograms = 'it_2256',
    FilmFestivals = 'it_2258',
    Fortnite = 'it_2260',
    Freediving = 'it_2261',
    Freelance = 'it_2262',
    Goiko = 'it_2267',
    GospelMusic = 'it_2268',
    Gym = 'it_2272',
    Gymnastics = 'it_2273',
    HarryPotter = 'it_2275',
    HeavyMetal = 'it_2276',
    Hockey = 'it_2277',
    HomeWorkouts = 'it_2278',
    HumanRights = 'it_2280',
    IceCream = 'it_2282',
    Inclusivity = 'it_2285',
    Investing = 'it_2289',
    JetSkiing = 'it_2293',
    Jogging = 'it_2294',
    Sports = 'it_23',
    KoreanFood = 'it_2302',
    LeagueOfLegends = 'it_2309',
    Literature = 'it_2311',
    LiveMusic = 'it_2312',
    Makeup = 'it_2314',
    Manga = 'it_2316',
    Marathons = 'it_2317',
    MartialArts = 'it_2318',
    Marvel = 'it_2319',
    Memes = 'it_2320',
    Metaverse = 'it_2321',
    Mindfulness = 'it_2322',
    Mountains = 'it_2325',
    MusicalInstrument = 'it_2327',
    MusicComposition = 'it_2328',
    Nfts = 'it_2334',
    Nintendo = 'it_2335',
    OnlineGaming = 'it_2338',
    OnlineShopping = 'it_2339',
    Paddleboarding = 'it_2343',
    Padel = 'it_2344',
    Painting = 'it_2346',
    Paragliding = 'it_2348',
    Pilates = 'it_2353',
    Pinterest = 'it_2354',
    PlayStation = 'it_2356',
    PoleDance = 'it_2357',
    SpanishOmelette = 'it_2359',
    Ramen = 'it_2360',
    Raves = 'it_2362',
    RealEstate = 'it_2363',
    Roblox = 'it_2365',
    RockMusic = 'it_2366',
    Climbing = 'it_2367',
    RollerSkating = 'it_2369',
    Sauna = 'it_2377',
    SciFi = 'it_2379',
    PersonalDevelopment = 'it_2382',
    Shisha = 'it_2386',
    Singing = 'it_2388',
    Skateboarding = 'it_2389',
    Skincare = 'it_2390',
    SocialDevelopment = 'it_2392',
    SocialMediaInterest = 'it_2393',
    SoundCloud = 'it_2396',
    Spa = 'it_2397',
    Spotify = 'it_2398',
    TableTennis = 'it_2404',
    TikTok = 'it_2414',
    TownFestivals = 'it_2416',
    Trap = 'it_2417',
    Twitch = 'it_2419',
    VirtualReality = 'it_2425',
    Volleyball = 'it_2426',
    WalkingTours = 'it_2427',
    Weightlifting = 'it_2430',
    WorldPeace = 'it_2431',
    Wrestling = 'it_2432',
    Writing = 'it_2433',
    Xbox = 'it_2434',
    EmpoweredYouth = 'it_2435',
    YouTube = 'it_2436',
    Pride = 'it_2437',
    TryingNewThings = 'it_26',
    KPop = 'it_27',
    Reading = 'it_28',
    Photography = 'it_29',
    Karaoke = 'it_3',
    HotSprings = 'it_30',
    Walking = 'it_31',
    CafeHopping = 'it_33',
    Instagram = 'it_35',
    Aquarium = 'it_36',
    Gastronomy = 'it_37',
    Running = 'it_4',
    Cocktails = 'it_4001',
    Yoga = 'it_42',
    Training = 'it_43',
    Swimming = 'it_48',
    Disney = 'it_50',
    Athletics = 'it_5002',
    SpringboardDiving = 'it_5006',
    Rowing = 'it_5013',
    SportShooting = 'it_5014',
    IceHockey = 'it_5021',
    Comedy = 'it_51',
    Netflix = 'it_53',
    Music = 'it_54',
    Cycling = 'it_55',
    Crafts = 'it_56',
    Picnics = 'it_57',
    Outdoors = 'it_58',
    LanguageExchange = 'it_6',
    Opera = 'it_6038',
    LatinMusic = 'it_6041',
    FolkMusic = 'it_6045',
    HouseMusic = 'it_6046',
    DanceMusic = 'it_6047',
    RnB = 'it_6048',
    Jazz = 'it_6052',
    ElectronicMusic = 'it_6056',
    IndieMusic = 'it_6057',
    Anime = 'it_62',
    Fashion = 'it_63',
    ActiveLifestyle = 'it_66',
    Travel = 'it_7',
    Baking = 'it_70',
    Sweets = 'it_7020',
    Mocktails = 'it_7022',
    BeachSports = 'it_7023',
    FitnessClasses = 'it_7024',
    Skating = 'it_7025',
    AlternativeMusic = 'it_7027',
    PopMusic = 'it_7036',
    PunkRock = 'it_7037',
    RapMusic = 'it_7039',
    SoulMusic = 'it_7040',
    MusicalTheater = 'it_7042',
    ActionMovies = 'it_7044',
    AnimatedMovies = 'it_7045',
    CrimeShows = 'it_7046',
    Documentaries = 'it_7047',
    DramaSeries = 'it_7048',
    FantasyMovies = 'it_7049',
    IndieMovies = 'it_7050',
    RealityShows = 'it_7051',
    RomComs = 'it_7052',
    SportsShows = 'it_7053',
    ThrillerMovies = 'it_7054',
    KDramas = 'it_7055',
    XContent = 'it_7056',
    ComicCons = 'it_7057',
    Blogging = 'it_71',
    Camping = 'it_72',
    RockClimbing = 'it_75',
    Concerts = 'it_76',
    CrossFit = 'it_78',
    Fishing = 'it_86',
    Hiking = 'it_88',
    Cinema = 'it_9',
    Nature = 'it_98',
    Nightlife = 'it_99',
}

/**
 * Descriptors that expose selectable `choices` (`de_*`), keyed by a friendly name.
 * Value = the Tinder descriptor id.
 */
export enum Descriptor {
    /** "Busco..." — what you're looking for. Choices: {@link LookingFor}. */
    LookingFor = 'de_29',
    /** "Tipo de relación" — relationship type. Choices: {@link RelationshipType}. */
    RelationshipType = 'de_38',
    /** "Horóscopo" — zodiac sign. Choices: {@link Zodiac}. */
    Zodiac = 'de_1',
    /** "Educación" — education. Choices: {@link Education}. */
    Education = 'de_9',
    /** "Planes de familia" — family plans. Choices: {@link FamilyPlans}. */
    FamilyPlans = 'de_33',
    /** "¿Cómo te comunicas?" — communication style. Choices: {@link Communication}. */
    Communication = 'de_2',
    /** "Lenguaje de amor" — love language. Choices: {@link LoveLanguage}. */
    LoveLanguage = 'de_35',
    /** "Mascotas" — pets. Choices: {@link Pets}. */
    Pets = 'de_3',
    /** "Beber" — drinking. Choices: {@link Drinking}. */
    Drinking = 'de_22',
    /** "¿Con qué frecuencia fumas?" — smoking. Choices: {@link Smoking}. */
    Smoking = 'de_11',
    /** "¿Haces deporte?" — workout. Choices: {@link Workout}. */
    Workout = 'de_10',
    /** "Redes sociales" — social media. Choices: {@link SocialMedia}. */
    SocialMedia = 'de_4',
    /** "Mis idiomas" — languages. Choices: {@link Language}. */
    Languages = 'de_37',
}

/** Choices for {@link Descriptor.LookingFor} (`de_29`). */
export enum LookingFor {
    LongTermPartner = '1',
    LongTermOpenToShortTerm = '2',
    ShortTermOpenToLongTerm = '3',
    ShortTermFun = '4',
    NewFriends = '5',
    StillFiguringItOut = '6',
}

/** Choices for {@link Descriptor.RelationshipType} (`de_38`). */
export enum RelationshipType {
    Monogamy = '1',
    EthicalNonMonogamy = '2',
    OpenRelationship = '3',
    Polyamory = '4',
    OpenToExploring = '5',
}

/** Choices for {@link Descriptor.Zodiac} (`de_1`). */
export enum Zodiac {
    Capricorn = '1',
    Aquarius = '2',
    Pisces = '3',
    Aries = '4',
    Taurus = '5',
    Gemini = '6',
    Cancer = '7',
    Leo = '8',
    Virgo = '9',
    Libra = '10',
    Scorpio = '11',
    Sagittarius = '12',
}

/** Choices for {@link Descriptor.Education} (`de_9`). */
export enum Education {
    BachelorsDegree = '1',
    InCollege = '2',
    HighSchool = '3',
    PhD = '4',
    PostGrad = '5',
    MastersDegree = '6',
    VocationalTraining = '7',
}

/** Choices for {@link Descriptor.FamilyPlans} (`de_33`). */
export enum FamilyPlans {
    WantChildren = '1',
    DontWantChildren = '2',
    HaveChildrenWantMore = '3',
    HaveChildrenDontWantMore = '4',
    NotSureYet = '5',
}

/** Choices for {@link Descriptor.Communication} (`de_2`). */
export enum Communication {
    BigTexter = '1',
    PhoneCaller = '3',
    VideoChatter = '2',
    BadTexter = '4',
    BetterInPerson = '5',
}

/** Choices for {@link Descriptor.LoveLanguage} (`de_35`). */
export enum LoveLanguage {
    ThoughtfulGestures = '1',
    Gifts = '2',
    Touch = '3',
    Compliments = '4',
    QualityTime = '5',
}

/** Choices for {@link Descriptor.Pets} (`de_3`). */
export enum Pets {
    Dog = '1',
    Cat = '2',
    Reptile = '3',
    Amphibian = '4',
    Bird = '8',
    Fish = '5',
    DontHaveButLoveThem = '9',
    Other = '11',
    Turtle = '12',
    Hamster = '13',
    Rabbit = '14',
    NoPets = '6',
    AllThePets = '7',
    WantAPet = '16',
    AllergicToPets = '17',
}

/** Choices for {@link Descriptor.Drinking} (`de_22`). */
export enum Drinking {
    NotForMe = '8',
    DontDrink = '9',
    SoberCurious = '10',
    OnSpecialOccasions = '11',
    SociallyOnWeekends = '12',
    MostNights = '13',
}

/** Choices for {@link Descriptor.Smoking} (`de_11`). */
export enum Smoking {
    SocialSmoker = '1',
    SmokeWhenDrinking = '2',
    NonSmoker = '3',
    Smoker = '4',
    TryingToQuit = '6',
}

/** Choices for {@link Descriptor.Workout} (`de_10`). */
export enum Workout {
    Everyday = '4',
    Often = '5',
    Sometimes = '6',
    GymRat = '1',
    Occasionally = '2',
    Never = '3',
}

/** Choices for {@link Descriptor.SocialMedia} (`de_4`). */
export enum SocialMedia {
    Influencer = '1',
    VeryActive = '2',
    NotOnSocialMedia = '3',
    Lurker = '4',
}

/** Choices for {@link Descriptor.Languages} (`de_37`). */
export enum Language {
    Afrikaans = '1',
    Albanian = '2',
    Amharic = '3',
    Arabic = '4',
    Armenian = '5',
    AmericanSignLanguage = '133',
    Assamese = '6',
    Aymara = '7',
    Azerbaijani = '8',
    Bambara = '9',
    Basque = '10',
    Belarusian = '11',
    Bengali = '12',
    Bhojpuri = '13',
    Bosnian = '14',
    Breton = '134',
    Bulgarian = '15',
    Burmese = '16',
    Cantonese = '17',
    Catalan = '18',
    Cebuano = '19',
    Chichewa = '20',
    Corsican = '21',
    Croatian = '22',
    Czech = '23',
    Danish = '24',
    Dhivehi = '25',
    Dogri = '26',
    Dutch = '27',
    English = '28',
    Esperanto = '29',
    Estonian = '30',
    Ewe = '31',
    Filipino = '32',
    Finnish = '33',
    French = '34',
    Frisian = '35',
    Galician = '36',
    Georgian = '37',
    German = '38',
    Greek = '39',
    Guarani = '40',
    Gujarati = '41',
    HaitianCreole = '42',
    Hausa = '43',
    Hawaiian = '44',
    Hebrew = '45',
    Hindi = '46',
    Hmong = '47',
    Hungarian = '48',
    Icelandic = '49',
    Igbo = '50',
    Ilocano = '51',
    Indonesian = '52',
    Irish = '53',
    Italian = '54',
    Japanese = '55',
    Javanese = '56',
    Kannada = '57',
    Kazakh = '58',
    Khmer = '59',
    Kinyarwanda = '60',
    Konkani = '61',
    Korean = '62',
    Krio = '63',
    Kurdish = '64',
    Kyrgyz = '65',
    Lao = '66',
    Latin = '67',
    Latvian = '68',
    Lingala = '69',
    Lithuanian = '70',
    Luganda = '71',
    Luxembourgish = '72',
    Macedonian = '73',
    Maithili = '74',
    Malagasy = '75',
    Malay = '76',
    Malayalam = '77',
    Maltese = '78',
    MandarinChinese = '79',
    Manipuri = '80',
    Maori = '81',
    Marathi = '82',
    Mizo = '83',
    Mongolian = '84',
    Nepali = '85',
    Norwegian = '86',
    Odia = '87',
    Oromo = '88',
    Pashto = '89',
    Persian = '90',
    Polish = '91',
    Portuguese = '92',
    Punjabi = '93',
    Quechua = '94',
    Romanian = '95',
    Russian = '96',
    Samoan = '97',
    Sanskrit = '98',
    ScottishGaelic = '99',
    NorthernSotho = '100',
    Serbian = '101',
    Sesotho = '102',
    Shona = '103',
    Sindhi = '104',
    Sinhala = '105',
    Slovak = '106',
    Slovenian = '107',
    Somali = '108',
    Spanish = '109',
    Sundanese = '110',
    Swahili = '111',
    Swedish = '112',
    Tajik = '113',
    Tamil = '114',
    Tatar = '115',
    Telugu = '116',
    Thai = '117',
    Tigrinya = '118',
    Tsonga = '119',
    Turkish = '120',
    Turkmen = '121',
    Twi = '122',
    Ukrainian = '123',
    Urdu = '124',
    Uyghur = '125',
    Uzbek = '126',
    Vietnamese = '127',
    Welsh = '128',
    Xhosa = '129',
    Yiddish = '130',
    Yoruba = '131',
    Zulu = '132',
}

/**
 * A single descriptor filter. The `id` accepts the friendly {@link Descriptor}
 * member or its raw `de_*` id, and `selectedChoices` is constrained per
 * descriptor to its matching choice enum (or the raw choice ids).
 */
export type DescriptorFilterInput =
    | { id: Descriptor.LookingFor | 'de_29'; selectedChoices: Array<LookingFor | ChoiceIdOf<'de_29'>> }
    | { id: Descriptor.RelationshipType | 'de_38'; selectedChoices: Array<RelationshipType | ChoiceIdOf<'de_38'>> }
    | { id: Descriptor.Zodiac | 'de_1'; selectedChoices: Array<Zodiac | ChoiceIdOf<'de_1'>> }
    | { id: Descriptor.Education | 'de_9'; selectedChoices: Array<Education | ChoiceIdOf<'de_9'>> }
    | { id: Descriptor.FamilyPlans | 'de_33'; selectedChoices: Array<FamilyPlans | ChoiceIdOf<'de_33'>> }
    | { id: Descriptor.Communication | 'de_2'; selectedChoices: Array<Communication | ChoiceIdOf<'de_2'>> }
    | { id: Descriptor.LoveLanguage | 'de_35'; selectedChoices: Array<LoveLanguage | ChoiceIdOf<'de_35'>> }
    | { id: Descriptor.Pets | 'de_3'; selectedChoices: Array<Pets | ChoiceIdOf<'de_3'>> }
    | { id: Descriptor.Drinking | 'de_22'; selectedChoices: Array<Drinking | ChoiceIdOf<'de_22'>> }
    | { id: Descriptor.Smoking | 'de_11'; selectedChoices: Array<Smoking | ChoiceIdOf<'de_11'>> }
    | { id: Descriptor.Workout | 'de_10'; selectedChoices: Array<Workout | ChoiceIdOf<'de_10'>> }
    | { id: Descriptor.SocialMedia | 'de_4'; selectedChoices: Array<SocialMedia | ChoiceIdOf<'de_4'>> }
    | { id: Descriptor.Languages | 'de_37'; selectedChoices: Array<Language | ChoiceIdOf<'de_37'>> };
